const config = require("../config.json");
const newsletterData = require("../schemas/newslettersubs");
const {
    EmbedBuilder,
    ActionRowBuilder,
    ButtonBuilder,
    ButtonStyle,
  } = require("discord.js");

async function ChooseRandomTopic(client) {
    const topicArray = [
        "How should governments prioritize environmental protection while balancing economic growth?",
        "What role should international cooperation play in combating climate change?",
        "What measures can be taken to reduce income inequality and ensure a more equitable society?",
        "Should the government intervene to redistribute wealth, and if so, to what extent?",
        "What are the advantages and disadvantages of implementing a universal healthcare system?",
        "How can healthcare be made more affordable and accessible without compromising quality?",
        "What should be the main considerations in developing immigration policies?",
        "How can countries balance the need for national security with compassion for migrants and refugees?",
        "What reforms can be implemented to address issues such as mass incarceration and racial disparities in the criminal justice system?",
        "How can rehabilitation and reintegration be prioritized over punishment?",
        "How can society balance the right to bear arms with ensuring public safety?",
        "What measures can be taken to prevent gun violence without infringing on individual liberties?",
        "What reforms are needed to improve the quality and accessibility of education?",
        "How should education funding be allocated to address disparities between schools?",
        "How can societies address systemic racism and promote racial equality?",
        "What policies and initiatives are effective in combating racial discrimination?",
        "What measures should be taken to protect and expand voting rights?",
        "How can electoral systems be reformed to ensure fair representation and minimize partisan influence?",
        "What role should government play in alleviating poverty and providing social safety nets?",
        "How can welfare programs be designed to encourage self-sufficiency while providing support to those in need?",
        "What reforms are necessary to address the influence of money in politics?",
        "How can transparency and accountability be increased in campaign financing and lobbying practices?",
        "How should governments balance the need for surveillance and security with individual privacy rights?",
        "What regulations should be in place to address emerging technologies like artificial intelligence and data collection?",
        "What are the appropriate limits on government surveillance in the interest of national security?",
        "How can civil liberties be protected while maintaining public safety?",
        "What are the core values and principles that should guide political decision-making?",
        "How can we strike a balance between individual rights and collective responsibilities?",
        "What role should government play in shaping society and addressing social issues?",
        "How can societies promote civic engagement and participation in the political process?",
        "How can we bridge political divides and foster constructive dialogue in polarized times?",
        "What strategies are effective in holding elected officials accountable for their actions?",
        "How can we promote transparency and integrity in political systems and institutions?",
        "What lessons can be learned from historical political movements and their impact on society?",
        "How can technology be leveraged to enhance democracy and civic participation?",
        "What responsibilities do individuals have in shaping political outcomes and promoting social change?",
        "How can societies effectively address the challenges of globalization and its impact on local economies and cultures?",
        "What is the role of activism and social movements in driving political change?",
        "What are the ethical considerations in political decision-making and policy implementation?",
        "How can governments foster innovation and technological advancements while addressing potential ethical and societal implications?",
        "What is the relationship between economic growth and environmental sustainability, and how can we find a balance?",
        "What is the role of education in shaping informed and engaged citizens?",
        "How can societies address the digital divide and ensure equitable access to technology and information?",
        "What are the implications of artificial intelligence and automation on employment and the future of work?",
        "How can societies navigate the tension between national sovereignty and global cooperation in addressing shared challenges?",
        "What is the role of the media in a democratic society, and how can we ensure unbiased and reliable information?",
        "How can societies foster a culture of respect and tolerance for diverse political perspectives?",
        "What are the ethical implications of emerging technologies, such as genetic engineering or artificial intelligence, in the political realm?",
        "How can societies address the challenges and opportunities of an aging population?",
        "What is the role of international organizations in promoting global cooperation and addressing transnational issues?",
        "How can societies strike a balance between economic development and environmental conservation?",
        "What are the responsibilities of citizens in upholding democratic values and safeguarding democratic institutions?",
        "How can political systems adapt to rapid societal changes, such as technological advancements or shifting demographics?",
        "What measures can be taken to enhance public trust in government and political institutions?",
        "How can societies address the challenges and opportunities presented by the increasing interconnectedness of the world?",
        "How can societies address the challenges of disinformation, fake news, and the erosion of trust in media and institutions?",
        "How can political systems promote social cohesion and address issues of social polarization and division?",
        "What policies can be implemented to promote affordable housing and address homelessness?",
        "How can societies address the challenges and opportunities of rapid urbanization?",
        "What are the responsibilities of developed nations in addressing global poverty and promoting economic development in less-developed countries?",
        "How can societies address the challenges of demographic shifts and multiculturalism?",
        "How can societies address systemic corruption and promote transparency in governance?",
        "What is the impact of globalization on national sovereignty and cultural identity?",
        "If you could change one aspect of the political system in your country, what would it be and why?",
        "What are the key factors that influence political ideologies and party affiliations?",
        "How does the media shape public opinion and influence political discourse?",
        "In your opinion, what are the biggest challenges facing democracy today?",
        "Should political leaders prioritize short-term goals or long-term vision when making decisions?",
        "How can societies effectively address the rise of populism and political polarization?",
        "What are the ethical considerations in political campaigning and messaging?",
        "Should corporations have a role in shaping political policies and influencing decision-making?",
        "How can societies strike a balance between economic growth and preserving cultural heritage?",
        "What are the implications of emerging technologies, such as blockchain or virtual reality, on political systems?",
        "How can governments effectively address the challenges of an aging population and changing demographics?",
        "Should political leaders prioritize national interests or global cooperation when making decisions?",
        "What is the role of grassroots activism and civil disobedience in challenging political norms and promoting change?",
        "How can societies promote intergenerational equity and ensure a sustainable future for future generations?",
        "What are the impacts of political apathy and low voter turnout on the democratic process?",
        "How can political systems adapt to rapid technological advancements and the changing nature of work?",
        "What is the role of international law and institutions in resolving conflicts and promoting global stability?",
        "Should political leaders be held to higher moral standards than the general population?",
        "Should there be limits on political campaign spending to ensure a level playing field?",
        "How can societies address the challenges of political disengagement and apathy among young people?",
        "What role should religion play in shaping political decisions and policies?",
        "How can societies promote transparency and accountability in government decision-making processes?",
        "What are the ethical considerations in the use of military force and intervention in other countries?",
        "How can political systems effectively address the influence of special interest groups and lobbying?",
        "What are the impacts of income inequality on social cohesion and political stability?",
        "Should there be term limits for political leaders to prevent the consolidation of power?",
        "How can societies strike a balance between protecting national security and upholding human rights in the context of counterterrorism efforts?",
        "What are the challenges and benefits of implementing direct democracy mechanisms in political decision-making?",
        "How can political systems address the influence of money in politics and reduce the risk of corruption?",
        "What are the implications of artificial intelligence and algorithms on political discourse and information consumption? (this post was made by an AI)",
        "Should political leaders prioritize environmental sustainability over short-term economic gains?",
        "What role should arts and culture play in shaping political narratives and fostering social change?",
        "How can societies balance the right to free speech with the need to combat hate speech and disinformation?",
        "What are the ethical considerations in the use of surveillance technologies for law enforcement purposes?",
        "Should there be limits on the power of social media platforms in shaping political discourse and information dissemination?",
        "How can societies effectively address the challenges of political polarization and promote constructive dialogue?",
        "What are the implications of global migration trends on political systems and social cohesion?",
        "Should there be a universal basic income to address income inequality and technological unemployment?",
        "How can societies strike a balance between economic development and the preservation of indigenous rights and cultural heritage?",
        "What role should civil society organizations and non-governmental organizations play in shaping political agendas?",
        "Should there be limits on the influence of corporate lobbying in political decision-making processes?",
        "What are the impacts of globalization on labor rights and workers' protections?",
        "How can societies address the challenges of online disinformation and manipulation in political campaigns?",
        "Should there be a global governance framework to address pressing global challenges, such as climate change or pandemics?",
        "What are the impacts of the gig economy and the rise of freelance work on social and political structures?",
        "How can political systems ensure the meaningful participation of marginalized and underrepresented communities in decision-making processes?",
        "What are the ethical considerations in the use of emerging technologies, such as genetic editing or brain-computer interfaces, in political contexts?",
        "How can societies effectively incorporate indigenous knowledge and perspectives into political decision-making processes?",
        "How can societies address the challenges of cultural assimilation while respecting the rights of minority communities?",
        "What are the implications of mass surveillance and data collection on individual privacy and civil liberties?",
        "Should there be a legal framework for the protection of digital rights and online freedom of expression?",
        "How can political systems address the challenges of inequality in access to quality education and opportunities for upward mobility?",
        "What role should intergenerational equity play in political decision-making and resource allocation?",
        "How can societies navigate the ethical implications of human genetic enhancement in the context of political decision-making?",
        "Should there be a global initiative for the regulation and management of emerging technologies, such as nanotechnology or quantum computing?",
        "How can political systems address the challenges posed by the automation of jobs and the potential for widespread unemployment?",
        "Should there be a global effort to establish a unified approach to tackling the issue of climate refugees?",
        "How can societies foster a sense of global citizenship and collective responsibility in addressing transnational challenges?",
        "Should there be international regulations and guidelines for the ethical use of big data in political campaigns and governance?",
        "Is the primary goal of the criminal justice system punishment, rehabilitation, or a combination of both? How should this balance be struck?",
        "What are the key factors contributing to racial disparities in arrests, sentencing, and incarceration rates? How can these disparities be addressed?",
        "Should non-violent drug offenses be treated primarily as a criminal justice issue or a public health issue? What are the implications of each approach?",
        "What are the benefits and drawbacks of implementing restorative justice practices in the criminal justice system? How can they be effectively integrated?",
        "How can the criminal justice system better support the reintegration of formerly incarcerated individuals into society and reduce recidivism rates?",
        "Should the use of cash bail be reformed or eliminated? What alternatives could be considered?",
        "What are the ethical considerations surrounding the use of technology, such as facial recognition or predictive algorithms, in law enforcement and criminal justice decision-making?",
        "How can community policing strategies enhance trust and collaboration between law enforcement and the communities they serve?",
        "Should there be limits on the use of solitary confinement in prisons? What alternatives can be explored?",
        "How can the criminal justice system effectively address mental health issues among individuals involved in the system?",
        "What role should rehabilitation and treatment programs play in addressing substance abuse and addiction within the criminal justice system?",
        "How can the criminal justice system adapt to effectively address cybercrime and emerging forms of criminal behavior in the digital age?",
        "Should there be stricter regulations and oversight for the use of force by law enforcement officers? How can police accountability be improved?",
        "How can the criminal justice system address the unique needs and circumstances of juvenile offenders?",
        "What are the impacts of private prisons and for-profit corrections on the fairness and effectiveness of the criminal justice system?",
        "What are the main arguments for and against the use of the death penalty as a form of punishment?",
        "Does the death penalty serve as an effective deterrent against violent crime? What evidence supports or challenges this claim?",
        "What are the ethical considerations surrounding the use of the death penalty? Is it morally justifiable to take a person's life as a form of punishment?",
        "How does the death penalty impact society, including victims' families and broader perceptions of justice?",
        "Should the death penalty be abolished or retained? What factors should be considered in making this decision?",
        "How does the death penalty interact with issues of racial bias and disparities within the criminal justice system?",
        "What are the potential risks of wrongful convictions and executing innocent individuals? How can such risks be mitigated?",
        "Is there a role for international law and human rights in influencing the use of the death penalty?",
        "What are the main arguments for and against the legality and accessibility of abortion?",
        "What are the ethical considerations surrounding the right to life of the fetus versus the bodily autonomy and reproductive rights of the pregnant individual?",
        "Should the decision to have an abortion be solely a personal choice, or should there be legal restrictions or regulations in place?",
        "How does the cultural and religious context influence perspectives on abortion? How can these perspectives be respected and reconciled in a diverse society?",
        "What are the implications of limiting or banning access to abortion on public health, including maternal health and safety?",
        "How can society provide adequate support and resources to individuals facing unplanned pregnancies, regardless of their decision regarding abortion?",
        "Should medical professionals have the right to refuse to provide or participate in abortions based on personal or religious beliefs? How should the balance be struck between professional obligations and individual convictions?",
        "What role should comprehensive sex education and access to contraception play in reducing the need for abortion?",
        "How can societies address the complex ethical and legal questions surrounding late-term abortions or cases involving fetal abnormalities?",
        "How can dialogue and understanding be fostered between individuals with differing viewpoints on abortion to encourage respectful and constructive conversations?",
        "Should Supreme Court justices be appointed for life? What are the advantages and disadvantages of lifetime appointments?",
        "How does the nomination and confirmation process for Supreme Court justices influence the balance of power and political dynamics?",
        "What role does the Supreme Court play in shaping and evolving societal values and norms?",
        "Should the Supreme Court have the power of judicial review to strike down laws passed by elected representatives? What are the implications of this power?",
        "How should the Supreme Court balance the need for judicial independence with accountability to the public and democratic institutions?",
        "How can the Supreme Court effectively navigate controversial and divisive issues while maintaining public trust and confidence?",
        "What are the consequences of a politically polarized Supreme Court and its impact on the perception of impartiality and fairness?",
        "How does the Supreme Court interact with and shape the interpretation of constitutional rights and protections?",
        "Should the Supreme Court play a more active role in promoting social justice and addressing systemic inequalities?",
        "How can the Supreme Court strike a balance between respecting precedent (stare decisis) and the need for evolving interpretations of the law?",
        "What are the implications of a divided Supreme Court, with justices appointed by different presidents and representing different judicial philosophies?",
        "How does public opinion and societal change influence the Supreme Court's decisions and interpretations of the law?",
        "Should the Supreme Court be subject to term limits to ensure regular turnover and prevent excessive influence by a few individuals?",
        "What role should diversity, including racial, gender, and ideological diversity, play in the composition of the Supreme Court?",
        "How should the Supreme Court navigate the tension between protecting individual rights and deferring to democratic processes and legislative decisions?",
        "Should there be reforms to the nomination and confirmation process to promote greater transparency and reduce political partisanship?",
        "How can the Supreme Court maintain its legitimacy and authority in an era of increasing political polarization and public skepticism?",
        "Should there be term limits for members of Congress? What are the advantages and disadvantages of term limits?",
        "How can Congress effectively balance the needs and interests of their constituents with the broader national agenda?",
        "Should the size of Congress be expanded or reduced? What are the implications of changing its size?",
        "How can Congress address the challenges of political polarization and partisan gridlock to foster effective governance?",
        "How can Congress improve its oversight and checks on the executive branch to ensure accountability?",
        "What is the role of compromise and bipartisanship in the legislative process, and how can they be encouraged in Congress?",
        "How can Congress improve transparency and public trust in its operations and decision-making?",
        "Should there be reforms to the process of executive branch appointments, including cabinet members and other key positions?",
        "How can societies balance the right to bear arms with the need for public safety and preventing gun violence?",
        "What are the implications of the Second Amendment and its interpretation on gun rights and gun control measures?",
        "How can background checks and mental health evaluations be effectively implemented in the process of acquiring firearms?",
        "Should there be stricter regulations on the sale and possession of certain types of firearms, such as assault weapons or high-capacity magazines?",
        "How can gun violence prevention measures be improved while respecting the rights of law-abiding gun owners?",
        "What are the impacts of gun violence on public health, communities, and individuals, and how can these be mitigated?",
        "Should concealed carry and open carry laws be more or less restricted? What are the benefits and drawbacks of each approach?",
        "How can gun safety education and training be enhanced to promote responsible gun ownership and prevent accidents?",
        "What role can technology, such as smart guns or improved gun tracking systems, play in enhancing gun safety and reducing illegal firearm use?",
        "How should freedom of speech be protected and balanced with the need to prevent hate speech or disinformation",
        "What are the ethical considerations surrounding the regulation of speech, such as limits on political campaign financing or restrictions on incitement to violence?",
        "How can societies navigate the tension between freedom of religion and the separation of church and state?",
        "Should there be limits on freedom of the press to prevent the spread of misinformation or protect national security? What are the potential risks and benefits of such limits?",
        "How can the freedom of assembly and the right to protest be effectively protected while maintaining public order and safety?",
        "What role does the First Amendment play in promoting a vibrant marketplace of ideas and fostering public discourse?",
        "How should schools and universities balance the freedom of expression with the need to create inclusive and respectful environments?",
        "What are the implications of the First Amendment in the digital age, including online speech and social media platforms?",
        "Should there be limitations or regulations on commercial speech, such as advertising or corporate influence in political campaigns?"
    ]

    const politicsChannel = client.guilds.cache.get("760275642150420520").channels.cache.get("964239900620759070")

    const message = await politicsChannel.messages.fetch(politicsChannel.lastMessageId)

    if (Date.now() - 3600000 > message.createdTimestamp) {
        const randomNumber = Math.floor(Math.random() * topicArray.length)
        const randomTopic = topicArray[randomNumber]

        const topicEmbed = new EmbedBuilder()
        .setTitle("New Discussion Prompt")
        .setColor("Green")
        .setDescription(`${randomTopic}`)

        politicsChannel.send({ embeds: [topicEmbed] })

    }

}

module.exports = {
    ChooseRandomTopic: ChooseRandomTopic
}